# Generated by Django 5.0.1 on 2024-02-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0002_article_author_delete_makale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
