# Generated by Django 5.0.1 on 2024-02-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0003_writer_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
